const storageKey = 'tw-buddy-state';
Page({
  data: { tab: '可申请同行', tabs: ['可申请同行', '我收到的申请', '我发出的申请', '同行聊天'], plans: [{ id: 'seed-hangzhou', title: '杭州旅行 · 10月3日', date: '10月3日 · 杭州东站集合', note: '西湖、龙井和城市散步，节奏舒适。', ownerId: 'other-user', owner: 'Mia' }], applications: [], chats: [], title: '', date: '', note: '' },
  onLoad() { const saved = wx.getStorageSync(storageKey) || {}; this.setData({ plans: (saved.plans || []).concat(this.data.plans), applications: saved.applications || [], chats: Object.values(saved.chats || {}) }); },
  choose(e) { this.setData({ tab: e.currentTarget.dataset.tab }); },
  input(e) { this.setData({ [e.currentTarget.dataset.key]: e.detail.value }); },
  publish() { if (!this.data.title) return wx.showToast({ title: '请填写旅行标题', icon: 'none' }); const saved = wx.getStorageSync(storageKey) || {}; const plan = { id: `plan-${Date.now()}`, title: this.data.title, date: this.data.date, note: this.data.note, ownerId: 'local-user', owner: '我' }; saved.plans = [plan].concat(saved.plans || []); wx.setStorageSync(storageKey, saved); this.setData({ title: '', date: '', note: '', plans: [plan].concat(this.data.plans) }); },
  apply(e) { const id = e.currentTarget.dataset.id; const plan = this.data.plans.find(item => item.id === id); const saved = wx.getStorageSync(storageKey) || {}; saved.applications = saved.applications || []; if (saved.applications.some(item => item.planId === id)) return wx.showToast({ title: '已经申请过了', icon: 'none' }); saved.applications.push({ id: `app-${Date.now()}`, planId: id, planTitle: plan.title, applicantId: 'local-user', applicant: '我', ownerId: plan.ownerId, status: '待处理' }); wx.setStorageSync(storageKey, saved); this.setData({ applications: saved.applications }); wx.showToast({ title: '申请已发送', icon: 'success' }); },
  decide(e) { const saved = wx.getStorageSync(storageKey) || {}; saved.applications = saved.applications || []; const app = saved.applications.find(item => item.id === e.currentTarget.dataset.id); if (!app) return; app.status = e.currentTarget.dataset.approved === 'true' ? '已同意' : '已拒绝'; saved.chats = saved.chats || {}; if (app.status === '已同意') saved.chats[app.planId] = { active: true, title: app.planTitle, messages: [] }; wx.setStorageSync(storageKey, saved); this.setData({ applications: saved.applications, chats: Object.values(saved.chats) }); },
  chat(e) { const chat = this.data.chats.find(item => item.title === e.currentTarget.dataset.title); if (!chat) return; wx.showModal({ title: chat.title, editable: true, placeholderText: '集合地点、交通、住宿…', success: result => { if (!result.confirm || !result.content) return; const saved = wx.getStorageSync(storageKey) || {}; saved.chats = saved.chats || {}; const target = Object.values(saved.chats).find(item => item.title === chat.title); target.messages = (target.messages || []).concat({ from: 'local-user', text: result.content, createdAt: new Date().toISOString() }); wx.setStorageSync(storageKey, saved); } }); }
});
