(function () {
  const base = location.protocol === 'file:' ? 'http://localhost:8787' : '';
  const key = 'tw-auth-session';
  let session = JSON.parse(localStorage.getItem(key) || 'null');
  async function request(path, options = {}) { const headers = { ...(options.headers || {}) }; if (!(options.body instanceof FormData)) headers['Content-Type'] = 'application/json'; if (session?.access_token) headers.Authorization = 'Bearer ' + session.access_token; const response = await fetch(base + path, { ...options, headers }); const body = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error || '请求失败'); return body; }
  function getDialog() { let node = document.getElementById('authDialog'); if (!node) { node = document.createElement('dialog'); node.id = 'authDialog'; node.style.cssText = 'border:0;border-radius:12px;padding:20px;width:min(390px,calc(100% - 32px));box-shadow:0 20px 60px #173f4f33'; document.body.appendChild(node); } return node; }
  function show(mode = 'login') { const node = getDialog(), registering = mode === 'register'; node.innerHTML = '<form id="authForm"><div class="head" style="margin:0 0 12px"><h2>' + (registering ? '注册 Travel World' : '登录 Travel World') + '</h2><button type="button" class="post-map" id="authClose">关闭</button></div>' + (registering ? '<input class="input" name="displayName" placeholder="昵称" required>' : '') + '<input class="input" name="email" type="email" placeholder="邮箱" required><input class="input" name="password" type="password" minlength="8" placeholder="密码（至少 8 位）" required><button class="btn" type="submit">' + (registering ? '创建账号' : '登录') + '</button> <button class="btn alt" type="button" id="authSwitch">' + (registering ? '已有账号' : '注册账号') + '</button><div id="authError" class="muted" style="margin-top:10px"></div></form>'; node.showModal(); node.querySelector('#authClose').onclick = () => node.close(); node.querySelector('#authSwitch').onclick = () => show(registering ? 'login' : 'register'); node.querySelector('#authForm').onsubmit = async event => { event.preventDefault(); const output = node.querySelector('#authError'); output.textContent = '正在连接…'; try { const result = await request('/api/auth/' + mode, { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); if (!result.session) { output.textContent = '注册成功，请完成邮箱验证后登录。'; return; } session = result.session; localStorage.setItem(key, JSON.stringify(session)); node.close(); render(); window.dispatchEvent(new Event('tw-auth-change')); } catch (error) { output.textContent = error.message; } }; }
  async function logout() { try { if (session) await request('/api/auth/logout', { method: 'POST' }); } catch (_) {} session = null; localStorage.removeItem(key); render(); window.dispatchEvent(new Event('tw-auth-change')); }
  function render() { const top = document.querySelector('.community-top'); if (!top) return; let button = document.getElementById('authEntry'); if (!button) { button = document.createElement('button'); button.id = 'authEntry'; button.className = 'post-map'; top.insertBefore(button, top.lastElementChild); } button.textContent = session ? '账号' : '登录'; button.onclick = session ? async () => { if (confirm('退出当前账号？')) { try { await request('/api/auth/logout', { method: 'POST' }); } catch (_) {} session = null; localStorage.removeItem(key); render(); window.dispatchEvent(new Event('tw-auth-change')); } } : () => show('login'); }
  window.TravelWorldAuth = { request, session: () => session, requireLogin: () => session ? true : (show('login'), false), showLogin: () => show('login'), logout }; render();
}());
