(function () {
  const auth = () => window.TravelWorldAuth;
  const safe = value => String(value || '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  let posts = [], selectedFile = null, favoriteIds = new Set(), currentFeed = 'recommend';
  function normalize(post) { const profile = post.profiles || {}, media = (post.post_media || []).sort((a, b) => a.sort_order - b.sort_order)[0]; return { ...post, user: profile.display_name || profile.username || '旅行者', text: post.content, location: post.location_name || [post.city, post.country].filter(Boolean).join(', '), image: media?.public_url, mediaType: media?.media_type, likes: (post.post_likes || []).length, liked: (post.post_likes || []).some(x => x.user_id === auth().session()?.user?.id), favorited: favoriteIds.has(post.id), comments: post.comments || [] }; }
  function render() { const target = document.getElementById('communityFeed'); if (!target) return; target.innerHTML = posts.length ? posts.map(raw => { const p = normalize(raw), media = p.image ? (p.mediaType === 'video' ? '<video class="post-image" controls preload="metadata" src="' + safe(p.image) + '"></video>' : '<img class="post-image" src="' + safe(p.image) + '" alt="' + safe(p.title) + '">') : ''; return '<article class="post-card">' + media + '<div class="post-content"><div class="post-author"><div><div class="post-author-name">' + safe(p.user) + '</div><button class="post-location post-map" onclick="openCommunityLocation(\'' + safe(p.city || p.location) + '\')">' + safe(p.location || '未标注地点') + '</button></div>' + (p.author_id !== auth().session()?.user?.id ? '<button class="post-map" onclick="toggleCommunityFollow(\'' + p.author_id + '\')">关注</button>' : '') + '</div><div class="post-title">' + safe(p.title) + '</div><div class="post-copy">' + safe(p.text) + '</div><div class="post-actions"><button class="' + (p.liked ? 'is-liked' : '') + '" onclick="toggleCommunityLike(\'' + p.id + '\')">' + (p.liked ? '♥' : '♡') + ' ' + p.likes + '</button><button onclick="toggleCommunityFavorite(\'' + p.id + '\')">' + (p.favorited ? '★ 已收藏' : '☆ 收藏') + '</button><span>评论 ' + p.comments.length + '</span><button onclick="openCommunityLocation(\'' + safe(p.city || p.location) + '\')" class="post-map">进入地图</button></div><div class="comment-row"><input data-comment-input="' + p.id + '" placeholder="写下你的旅行感受"><button onclick="addCommunityComment(\'' + p.id + '\')">评论</button></div>' + (p.comments.length ? '<div class="muted" style="font-size:12px;margin-top:10px">' + p.comments.slice(-2).map(c => '<div>· ' + safe(c.content) + '</div>').join('') + '</div>' : '') + '</div></article>'; }).join('') : '<div class="card"><div class="muted">还没有旅行分享，登录后发布第一篇内容。</div></div>'; }
  async function load() { try { posts = await auth().request(currentFeed === 'following' ? '/api/community/feed/following' : '/api/community/feed'); favoriteIds = new Set(auth().session?.() ? (await auth().request('/api/community/favorites')).map(post => post.id) : []); render(); } catch (e) { document.getElementById('communityFeed').innerHTML = '<div class="card"><div class="muted">暂时无法连接社区服务：' + safe(e.message) + '</div></div>'; } }
  window.setFeed = async feed => { if (feed === 'following' && !auth().requireLogin()) return; currentFeed = feed; document.getElementById('recommendTab')?.classList.toggle('active', feed === 'recommend'); document.getElementById('followingTab')?.classList.toggle('active', feed === 'following'); await load(); };
  window.toggleComposer = () => { if (auth().requireLogin()) document.getElementById('composePanel').classList.toggle('open'); };
  window.selectCommunityMedia = event => { selectedFile = event.target.files?.[0] || null; document.getElementById('composeMediaHint').textContent = selectedFile ? selectedFile.name + ' 已选择' : '可选择一张照片或短视频'; };
  window.publishPost = async () => { if (!auth().requireLogin()) return; const title = document.getElementById('composeTitle').value.trim(), content = document.getElementById('composeText').value.trim(), location_name = document.getElementById('composeLocation').value.trim(); if (!title || !content) return alert('请填写标题和内容'); try { const post = await auth().request('/api/community/posts', { method: 'POST', body: JSON.stringify({ title, content, location_name, city: location_name.split(',')[0], type: selectedFile?.type.startsWith('video/') ? 'video' : selectedFile ? 'photo' : 'story' }) }); if (selectedFile) { const form = new FormData(); form.append('file', selectedFile); await auth().request('/api/community/posts/' + post.id + '/media', { method: 'POST', body: form }); } ['composeTitle','composeText','composeLocation'].forEach(id => document.getElementById(id).value = ''); selectedFile = null; document.getElementById('composePanel').classList.remove('open'); await load(); } catch (e) { alert('发布失败：' + e.message); } };
  window.toggleCommunityLike = async id => { if (!auth().requireLogin()) return; try { await auth().request('/api/community/posts/' + id + '/like', { method: 'POST' }); await load(); } catch (e) { alert(e.message); } };
  window.toggleCommunityFavorite = async id => { if (!auth().requireLogin()) return; try { await auth().request('/api/community/posts/' + id + '/favorite', { method: 'POST' }); await load(); } catch (e) { alert(e.message); } };
  window.addCommunityComment = async id => { if (!auth().requireLogin()) return; const input = document.querySelector('[data-comment-input="' + id + '"]'); if (!input?.value.trim()) return; try { await auth().request('/api/community/posts/' + id + '/comments', { method: 'POST', body: JSON.stringify({ content: input.value.trim() }) }); await load(); } catch (e) { alert(e.message); } };
  window.toggleCommunityFollow = async id => { if (!auth().requireLogin()) return; try { await auth().request('/api/community/users/' + id + '/follow', { method: 'POST' }); } catch (e) { alert(e.message); } };
  window.openCommunityLocation = city => { go('map'); loadMap(); setTimeout(() => window.searchTravelMap?.(city), 400); };
  window.addEventListener('tw-auth-change', load); load();
}());
