(function () {
  const auth=()=>window.TravelWorldAuth, safe=value=>window.TravelPostUI.safe(value);
  let editingId=null, selected=[], calculation=null, map=null, markers=[], line=null, returnToPublisher=false;
  const transportLabels={walking:'步行',cycling:'骑行',driving:'驾车',transit:'公共交通'};
  function inject(){
    if(document.getElementById('routeEditor'))return;
    const editor=document.createElement('section');editor.id='routeEditor';editor.className='screen route-workspace';editor.innerHTML='<div class="route-page-head"><button onclick="closeRouteEditor()">‹</button><div><small>ROUTE STUDIO</small><h1>路线编辑器</h1></div><button class="route-save" id="routeSave" onclick="saveRouteEditor()">保存</button></div><input id="routeTitle" class="input" placeholder="路线名称，例如：京都岚山一日漫游"><div class="route-mode" id="routeMode">'+Object.entries(transportLabels).map(([key,label],i)=>'<button data-mode="'+key+'" class="'+(i===2?'active':'')+'" onclick="selectRouteMode(\''+key+'\')">'+label+'</button>').join('')+'</div><div class="route-search"><input id="routeSearch" class="input" placeholder="搜索城市、景点或地址"><button class="btn" onclick="searchRoutePlace()">添加地点</button></div><div id="routeSearchResults"></div><div id="routeEditorMap" class="route-editor-map"><div class="muted">地图加载中…</div></div><div class="route-editor-caption">点击地图也可以添加地点；拖动顺序可用上下按钮精确调整。</div><div id="routeWaypoints" class="route-waypoints"></div><div id="routeSummary" class="route-summary"></div>';
    const detail=document.createElement('section');detail.id='routeDetail';detail.className='screen route-workspace';detail.innerHTML='<div id="routeDetailContent"></div>';
    document.querySelector('main.app').append(editor,detail);
  }
  function mode(){return document.querySelector('#routeMode .active')?.dataset.mode||'driving';}
  window.selectRouteMode=value=>{document.querySelectorAll('#routeMode button').forEach(button=>button.classList.toggle('active',button.dataset.mode===value));calculate();};
  function renderPoints(){
    const root=document.getElementById('routeWaypoints');if(!root)return;
    root.innerHTML=selected.length?selected.map((point,index)=>'<div class="route-waypoint"><span>'+(index+1)+'</span><div><b>'+safe(point.name)+'</b><small>'+safe(point.address||point.displayName||'地图选点')+'</small></div><div><button onclick="moveRoutePoint('+index+',-1)" '+(index===0?'disabled':'')+'>↑</button><button onclick="moveRoutePoint('+index+',1)" '+(index===selected.length-1?'disabled':'')+'>↓</button><button onclick="removeRoutePoint('+index+')">×</button></div></div>').join(''):'<div class="route-empty">搜索或点击地图，至少添加两个地点。</div>';
    renderMap();calculate();
  }
  function initMap(){
    const root=document.getElementById('routeEditorMap');if(!root||root.offsetParent===null)return;
    if(!window.L)return setTimeout(initMap,150);
    if(!map){root.innerHTML='';map=L.map(root,{zoomControl:true,worldCopyJump:true}).setView([28,105],3);L.tileLayer('/api/map/tiles/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);map.on('click',async event=>{const {lat,lng}=event.latlng;let name=`${lat.toFixed(4)}, ${lng.toFixed(4)}`;try{const place=await auth().request(`/api/map/reverse?latitude=${lat}&longitude=${lng}`);name=place.city||place.country||name;}catch(_){}selected.push({name,address:'地图选点',latitude:lat,longitude:lng,provider:'OpenStreetMap'});renderPoints();});}
    setTimeout(()=>map.invalidateSize(),50);renderMap();
  }
  function renderMap(){if(!map)return;markers.forEach(marker=>marker.remove());markers=[];selected.forEach((point,index)=>markers.push(L.marker([point.latitude,point.longitude]).addTo(map).bindTooltip(`${index+1}. ${point.name}`)));if(line){line.remove();line=null;}const coords=calculation?.geometry?.coordinates;if(Array.isArray(coords)){line=L.polyline(coords.map(pair=>[pair[1],pair[0]]),{color:'#a34837',weight:5,opacity:.86}).addTo(map);}else if(selected.length>1){line=L.polyline(selected.map(point=>[point.latitude,point.longitude]),{color:'#a34837',weight:4,dashArray:'8 7'}).addTo(map);}const layers=[...markers,line].filter(Boolean);if(layers.length)map.fitBounds(L.featureGroup(layers).getBounds().pad(.18));}
  let calculationToken=0;
  async function calculate(){const token=++calculationToken, summary=document.getElementById('routeSummary');calculation=null;if(selected.length<2){if(summary)summary.innerHTML='';renderMap();return;}if(summary)summary.textContent='正在计算真实道路路线…';try{const result=await auth().request('/api/map/route',{method:'POST',body:JSON.stringify({points:selected,mode:mode()})});if(token!==calculationToken)return;calculation=result;summary.innerHTML='<b>'+transportLabels[mode()]+(result.fallback?' · 驾车估算':'')+'</b><span>'+ (result.distanceMeters/1000).toFixed(1)+' km</span><span>'+Math.max(1,Math.round(result.durationSeconds/60))+' 分钟</span>';renderMap();}catch(error){if(token===calculationToken){summary.textContent='道路路线暂不可用，将保存地点顺序：'+error.message;renderMap();}}}
  window.searchRoutePlace=async()=>{const input=document.getElementById('routeSearch'),root=document.getElementById('routeSearchResults'),query=input.value.trim();if(query.length<2)return auth().toast('请输入至少两个字符');root.innerHTML='<div class="muted">正在搜索真实地点…</div>';try{const data=await auth().request('/api/map/search?q='+encodeURIComponent(query));root.innerHTML=data.results.map((point,index)=>'<button class="route-search-result" data-index="'+index+'"><b>'+safe(point.name)+'</b><small>'+safe(point.displayName)+'</small><span>＋</span></button>').join('');root.querySelectorAll('button').forEach(button=>button.onclick=()=>{selected.push(data.results[Number(button.dataset.index)]);root.innerHTML='';input.value='';renderPoints();});}catch(error){root.textContent=error.message;}};
  window.moveRoutePoint=(index,delta)=>{const target=index+delta;if(target<0||target>=selected.length)return;[selected[index],selected[target]]=[selected[target],selected[index]];renderPoints();};
  window.removeRoutePoint=index=>{selected.splice(index,1);renderPoints();};
  window.openRouteEditor=async (id=null,options={})=>{if(!auth().requireLogin())return;inject();editingId=id;returnToPublisher=options.returnToPublisher===true;selected=[];calculation=null;document.getElementById('routeTitle').value='';selectRouteMode('driving');go('routeEditor');initMap();if(id){try{const route=await auth().request('/api/routes/'+id);document.getElementById('routeTitle').value=route.title||'';selectRouteMode(route.transport_mode||'driving');selected=window.TravelPostUI.points(route).map(point=>({...point}));calculation=route.geometry?{geometry:route.geometry,distanceMeters:route.distance_meters,durationSeconds:route.duration_seconds}:null;renderPoints();}catch(error){auth().toast('路线加载失败：'+error.message);}}else renderPoints();};
  window.closeRouteEditor=()=>go(returnToPublisher?'publish':'profile');
  window.saveRouteEditor=async()=>{const title=document.getElementById('routeTitle').value.trim(),button=document.getElementById('routeSave');if(!title)return auth().toast('请填写路线名称');if(selected.length<2)return auth().toast('至少添加两个地点');button.disabled=true;button.textContent='保存中…';const payload={title,destination:selected.at(-1).name,transport_mode:mode(),points:selected,geometry:calculation?.geometry||null,distance_meters:calculation?.distanceMeters||0,duration_seconds:calculation?.durationSeconds||0};try{const route=await auth().request('/api/routes'+(editingId?'/'+editingId:''),{method:editingId?'PATCH':'POST',body:JSON.stringify(payload)});auth().toast('路线已保存');if(returnToPublisher){window.selectPublishRoute?.(route);go('publish');}else{openRouteDetail(route.id);}}catch(error){auth().toast('保存失败：'+error.message);}finally{button.disabled=false;button.textContent='保存';}};
  window.openRouteDetail=async id=>{inject();go('routeDetail');const root=document.getElementById('routeDetailContent');root.innerHTML='<div class="muted">正在加载路线…</div>';try{const route=await auth().request('/api/routes/'+id),places=window.TravelPostUI.points(route);root.innerHTML='<div class="route-page-head"><button onclick="go(\'home\')">‹</button><div><small>TRAVEL ROUTE</small><h1>'+safe(route.title)+'</h1></div>'+(route.owner_id===auth().session?.()?.user?.id?'<button class="route-save" onclick="openRouteEditor(\''+route.id+'\')">编辑</button>':'')+'</div>'+window.TravelPostUI.routeCard(route)+'<div id="routeDetailMap" class="route-editor-map"></div><div class="route-detail-meta"><b>'+safe(transportLabels[route.transport_mode]||'旅行路线')+'</b><span>'+safe(window.TravelPostUI.routeStats(route))+'</span><span>由 '+safe(route.owner?.display_name||'旅行者')+' 创建</span></div><div class="route-detail-list">'+places.map((place,index)=>'<div><span>'+(index+1)+'</span><section><b>'+safe(place.name)+'</b><small>'+safe(place.address||place.category||'路线地点')+'</small></section></div>').join('')+'</div>'+(route.posts?.length?'<div class="head"><h2>关联旅行记录</h2></div>'+route.posts.map(post=>window.TravelPostUI.card({...post,profiles:route.owner,author_id:route.owner_id,route:null},{showFollow:false})).join(''):'');setTimeout(()=>{if(!window.L)return;const node=document.getElementById('routeDetailMap'),detailMap=L.map(node).setView([25,105],3);L.tileLayer('/api/map/tiles/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(detailMap);const coords=route.geometry?.coordinates?.map(pair=>[pair[1],pair[0]])||places.map(p=>[p.latitude,p.longitude]);places.forEach((p,i)=>L.marker([p.latitude,p.longitude]).addTo(detailMap).bindTooltip(`${i+1}. ${p.name}`));if(coords.length>1){const path=L.polyline(coords,{color:'#a34837',weight:5}).addTo(detailMap);detailMap.fitBounds(path.getBounds().pad(.15));}},80);}catch(error){root.innerHTML='<button class="btn alt" onclick="go(\'home\')">返回</button><p>'+safe(error.message)+'</p>';}};
  inject();
}());
