(function () {
  const en={
    '首页':'Home','探索':'Explore','聊天':'Messages','旅友':'Buddies','我的':'Profile','发布':'Publish','登录':'Sign in','关闭':'Close','注册账号':'Create account','已有账号':'Already registered','登录 Travel World':'Sign in to Travel World','注册 Travel World':'Create a Travel World account','创建账号':'Create account','昵称':'Display name','邮箱':'Email','密码（至少 8 位）':'Password (8+ characters)','返回':'Back','← 返回':'← Back','← 返回地图':'← Back to map','打开 Q 版地图，':'Open the Q Atlas,','遇见下一站。':'meet your next stop.','使用原有地图数据与地图模型，搜索、缩放或点击 Q 版地标探索世界。':'Search, zoom, or tap a Q landmark to explore the world.','搜索':'Search','定位':'Locate','共享我的位置':'Share my location','国家筛选':'Country','在线用户':'Online users','规划这次旅行':'Plan this journey','目的地':'Destination','预算':'Budget','出发日期':'Departure date','旅行天数':'Trip length','兴趣':'Interests','生成 AI 路线':'Generate AI route','参考路线':'Curated routes','国内 · 海外':'China · Worldwide','全部':'All','城市旅行':'City','自然风景':'Nature','美食旅行':'Food','文化旅行':'Culture','独自旅行':'Solo','家庭旅行':'Family','摄影旅行':'Photography','户外旅行':'Outdoor','查看路线':'View route','查看详情':'View details','旅行者路线':'Traveler routes','真实发布':'Community','还没有旅行者发布公开路线。':'No public traveler routes yet.','打开旅行助手':'Open travel assistant','旅行助手':'Travel assistant','设置':'Settings','语言':'Language','简体中文':'简体中文','我的旅行':'My trips','我的路线':'My routes','我的收藏':'Saved','我的同行':'My buddies','我的申请':'Requests','我的发布':'My posts','关注':'Following','已关注':'Following','粉丝':'Followers','点赞评论':'Likes & comments','账号与个人资料':'Account & profile','账号与安全':'Account & security','隐私设置':'Privacy','黑名单':'Blocked accounts','体验偏好':'Preferences','退出登录':'Sign out','评论':'Comment','收藏':'Save','取消收藏':'Remove saved','已收藏':'Saved','地图':'Map','完整详情':'Details','关注/取消关注':'Follow / unfollow','私聊':'Message','返回消息列表':'Back to messages','删除':'Delete','发送':'Send','还没有来信':'No messages yet','登录查看':'Sign in to view','发布旅行记录':'Publish a travel story','标题（选填）':'Title (optional)','地点（选填），例如 Kyoto, Japan':'Location (optional), e.g. Kyoto, Japan','＋ 添加照片 / 视频':'+ Add photos / video','发布到首页':'Publish','加入我的路线':'Add to my route','加入我的旅行路线':'Add to my trip','让 AI 规划这里':'Plan this place with AI','用这个地点生成 AI 路线':'Plan this place with AI','推荐玩法':'What to do','建议时长':'Suggested time','最佳时间':'Best time','住宿区域':'Where to stay','到达建议':'Getting there','当地美食':'Local food','周边值得去':'Nearby places','地图位置':'Map location','打开地图 ↗':'Open map ↗','相关热门路线':'Related routes','热门图片暂时不可用':'Photos are temporarily unavailable','返回参考路线':'Back to routes','按这条路线继续规划':'Continue with this route','吃什么':'Food','住哪里':'Stay','交通':'Transport','建议停留':'Suggested stay','门票参考':'Ticket guide','怎么去':'Getting there','旅行提示':'Travel tip','注意事项':'Notes','重新规划':'Replan','查看完整地图':'View full map',
    '同路人':'Travel World','旅途手帖':'Travel Journal','山海之间':'Between Mountains & Sea','沿途风景，日常记录。':'Scenes and stories along the way.','探索目的地':'Explore destinations','推荐':'For you','查看帖子详情':'View post details','旅行记录':'Travel story','写下你的旅行感受':'Share your travel thoughts','更换':'Change','更换头像':'Change avatar','编辑昵称':'Edit name','登录 / 注册':'Sign in / Create account','获赞':'Likes','通知':'Notifications','消息':'Messages','内容偏好':'Content preferences','通用设置':'General','默认货币':'Default currency','清除缓存':'Clear cache','关于 Travel World':'About Travel World','关于我们':'About us','用户协议':'Terms of service','隐私政策':'Privacy policy','中国版':'China Edition','路线与预算显示货币':'Currency used for routes and budgets','本地保存':'Local storage','版本、语言、货币和最近路线只保存在此浏览器。':'Edition, language, currency, and recent routes are saved in this browser.','Visa':'Visa','微信支付':'WeChat Pay','支付宝':'Alipay','当地现金':'Local cash','目的地选集':'Destination collection','世界游览图':'World atlas','旅途书信':'Travel letters','同路人名录':'Travel buddies','我的旅册':'My travel book','加载中…':'Loading…','加载失败，请重试':'Could not load. Try again.','操作失败，请重试':'Something went wrong. Try again.','暂无内容':'Nothing here yet','保存':'Save','分享':'Share','使用此路线':'Use this route','让 AI 修改路线':'Modify with AI'
  };
  const attrs={placeholder:{'搜索城市或地标':'Search cities or landmarks','输入目的地，例如大理':'Enter a destination, e.g. Dali','预算（CNY）':'Budget (CNY)','旅行天数':'Trip length','兴趣，例如自然、美食、摄影':'Interests, e.g. nature, food, photography','写下此刻的见闻、感受或建议…':'Share what you saw, felt, or learned…','写下沿途见闻…':'Write a message…','写下你的旅行感受':'Share your travel thoughts','国家筛选':'Country'},'aria-label':{'打开旅行助手':'Open travel assistant','显示旅行助手':'Show travel assistant','返回上一页':'Go back','在线用户国家筛选':'Filter online users by country','发布内容':'Publish content','查看帖子详情':'View post details'}};
  const zh=Object.fromEntries(Object.entries(en).map(([key,value])=>[value,key]));let busy=false;
  function language(){try{return(JSON.parse(localStorage.getItem('tw-state')||'{}').lang||'zh')==='en'?'en':'zh';}catch(_){return'zh';}}
  const patterns=[
    [/^评论\s*(\d+)$/,'$1 comments',/^(\d+) comments$/,'评论 $1'],
    [/^(\d+)\s*天$/,'$1 days',/^(\d+) days$/,'$1 天'],
    [/^预算\s+(.+)$/,'Budget $1',/^Budget\s+(.+)$/,'预算 $1'],
    [/^兴趣[：:]\s*(.+)$/,'Interests: $1',/^Interests:\s*(.+)$/,'兴趣：$1'],
    [/^推荐[：:]\s*(.+)$/,'Best: $1',/^Best:\s*(.+)$/,'推荐：$1'],
    [/^旅行者路线暂时无法加载[：:]\s*(.+)$/,'Traveler routes are unavailable: $1',/^Traveler routes are unavailable:\s*(.+)$/,'旅行者路线暂时无法加载：$1']
    ,[/^在线地图\s*·\s*已加载\s*(\d+)\s*个地标；地图数据支持本地缓存。$/,'Online map · $1 landmarks loaded; map data is cached locally.',/^Online map · (\d+) landmarks loaded; map data is cached locally\.$/,'在线地图 · 已加载 $1 个地标；地图数据支持本地缓存。']
    ,[/^已显示\s*(\d+)\s*位主动共享位置的在线用户；点击 Q 版标识可互动。$/,'$1 users are sharing their location; tap a Q avatar to connect.',/^(\d+) users are sharing their location; tap a Q avatar to connect\.$/,'已显示 $1 位主动共享位置的在线用户；点击 Q 版标识可互动。']
  ];
  function translated(value){const dict=language()==='en'?en:zh;if(dict[value])return dict[value];for(const [zr,er,enr,zv] of patterns){const rule=language()==='en'?[zr,er]:[enr,zv];if(rule[0].test(value))return value.replace(rule[0],rule[1]);}return value;}
  function translate(root=document){if(busy)return;busy=true;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{const raw=node.nodeValue,trim=raw.trim(),next=translated(trim);if(next!==trim)node.nodeValue=raw.replace(trim,next);});root.querySelectorAll?.('[placeholder],[aria-label],[title]').forEach(node=>Object.entries(attrs).forEach(([attr,map])=>{const value=node.getAttribute(attr),table=language()==='en'?map:Object.fromEntries(Object.entries(map).map(([a,b])=>[b,a]));if(table[value])node.setAttribute(attr,table[value]);else if(value){const next=translated(value);if(next!==value)node.setAttribute(attr,next);}}));document.documentElement.lang=language()==='en'?'en':'zh-CN';busy=false;}
  const original=window.setLang;window.setLang=function(value){original?.(value);queueMicrotask(()=>translate());};
  new MutationObserver(records=>{if(!busy)records.forEach(record=>{record.addedNodes.forEach(node=>{if(node.nodeType===1)translate(node);else if(node.nodeType===3)translate(record.target);});});}).observe(document.body,{childList:true,subtree:true});translate();window.TravelWorldI18n={translate,language,t:key=>(language()==='en'?en[key]:key)||key};
}());
