(function () {
  let profile = null;
  let stats = { trips: 0, followers: 0, likes: 0 };
  const safe = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const labels = {
    zh: { title: '我的旅行空间', bio: '在路上，也在分享路上的风景。', travel: '我的旅行', routes: '我的路线', saved: '我的收藏', buddies: '我的同行', sent: '我的申请', posts: '我的发布', following: '关注', followers: '粉丝', interactions: '点赞评论', received: '同行申请', invites: '同行邀请', settings: '设置', account: '账号与安全', language: '语言设置', notice: '通知设置', privacy: '隐私设置', messages: '消息设置', preference: '内容偏好', block: '黑名单', general: '通用设置', about: '关于我们', terms: '用户协议', policy: '隐私政策', clear: '清除缓存', logout: '退出登录' },
    en: { title: 'My Travel Space', bio: 'On the road, sharing the view along the way.', travel: 'My trips', routes: 'My routes', saved: 'Saved', buddies: 'Travel buddies', sent: 'My applications', posts: 'My posts', following: 'Following', followers: 'Followers', interactions: 'Likes & comments', received: 'Buddy requests', invites: 'Buddy invites', settings: 'Settings', account: 'Account & security', language: 'Language', notice: 'Notifications', privacy: 'Privacy', messages: 'Messages', preference: 'Content preferences', block: 'Blocked users', general: 'General', about: 'About us', terms: 'Terms of use', policy: 'Privacy policy', clear: 'Clear cache', logout: 'Log out' }
  };
  function currentLang() { return (JSON.parse(localStorage.getItem('tw-state') || '{}').lang || 'zh'); }
  function render() {
    const section = document.getElementById('profile'); if (!section) return;
    const t = labels[currentLang()];
    const currency = (JSON.parse(localStorage.getItem('tw-state') || '{}').currency || 'CNY');
    const avatar = profile?.avatar_url || 'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect width="100%" height="100%" fill="#e8eee9"/><text x="50%" y="56%" text-anchor="middle" font-size="54" fill="#173f4f">TW</text></svg>');
    const name = profile?.display_name || profile?.username || (window.TravelWorldAuth?.session?.() ? '旅行者' : 'Travel World');
    const bio = profile?.bio || (window.TravelWorldAuth?.session?.() ? t.bio : '登录后建立你的旅行身份。');
    section.innerHTML = '<div class="eyebrow">MY SPACE</div><div class="profile-hero"><img src="' + safe(avatar) + '" class="profile-large-avatar"><div><h1>' + safe(name) + '</h1><p>' + safe(bio) + '</p></div></div><div class="profile-stats card"><div><b>' + stats.trips + '</b><span>' + t.travel + '</span></div><div><b>' + stats.followers + '</b><span>' + t.followers + '</span></div><div><b>' + stats.likes + '</b><span>获赞</span></div></div><div class="profile-links card"><button onclick="go(\'friends\')">✈ <span>' + t.buddies + '</span><small>旅行计划与同行关系</small></button><button onclick="go(\'ai\')">⌁ <span>' + t.routes + '</span><small>保存的路线与计划</small></button><button onclick="showProfileNotice(\'收藏内容\')">♡ <span>' + t.saved + '</span><small>旅行灵感</small></button><button onclick="showProfileNotice(\'我的发布\')">▧ <span>' + t.posts + '</span><small>照片、文章和路线</small></button><button onclick="showProfileNotice(\'关注与粉丝\')">◎ <span>' + t.following + ' · ' + t.followers + '</span><small>' + t.interactions + '</small></button><button onclick="go(\'friends\')">◌ <span>' + t.received + '</span><small>申请记录</small></button></div><div class="profile-settings card"><h3>' + t.settings + '</h3><button onclick="editTravelProfile()">个人中心<span>›</span></button><button onclick="showProfileNotice(\'' + t.account + '\')">' + t.account + '<span>›</span></button><button onclick="toggleProfileLanguage()">' + t.language + '<span>' + (currentLang() === 'zh' ? '简体中文' : 'English') + ' ›</span></button><button onclick="changeProfileCurrency()">默认货币<span>' + currency + ' ›</span></button><button onclick="showProfileNotice(\'' + t.notice + '\')">' + t.notice + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.privacy + '\')">' + t.privacy + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.messages + '\')">' + t.messages + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.preference + '\')">' + t.preference + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.block + '\')">' + t.block + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.general + '\')">' + t.general + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.about + '\')">' + t.about + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.terms + '\')">' + t.terms + '<span>›</span></button><button onclick="showProfileNotice(\'' + t.policy + '\')">' + t.policy + '<span>›</span></button><button onclick="clearProfileCache()">' + t.clear + '<span>›</span></button><button class="danger" onclick="logoutProfile()">' + t.logout + '<span>›</span></button></div>';
  }
  async function loadProfile() { if (!window.TravelWorldAuth?.session?.()) { profile = null; stats = { trips: 0, followers: 0, likes: 0 }; return render(); } try { [profile, stats] = await Promise.all([window.TravelWorldAuth.request('/api/users/me'), window.TravelWorldAuth.request('/api/users/me/stats')]); } catch (_) {} render(); }
  window.editTravelProfile = async () => { if (!window.TravelWorldAuth.requireLogin()) return; const name = prompt('昵称', profile?.display_name || ''); if (name === null) return; const bio = prompt('个人简介', profile?.bio || ''); if (bio === null) return; try { profile = await window.TravelWorldAuth.request('/api/users/me', { method: 'PATCH', body: JSON.stringify({ display_name: name.trim(), bio: bio.trim() }) }); const picker = document.createElement('input'); picker.type = 'file'; picker.accept = 'image/*'; picker.onchange = async () => { if (!picker.files[0]) return loadProfile(); const form = new FormData(); form.append('file', picker.files[0]); try { profile = await window.TravelWorldAuth.request('/api/users/me/avatar', { method: 'POST', body: form }); render(); } catch (error) { alert(error.message); } }; if (confirm('资料已保存。现在更换头像吗？')) picker.click(); else render(); } catch (error) { alert(error.message); } };
  window.showProfileNotice = title => alert(title + '页面正在逐步接入真实服务。');
  window.changeProfileCurrency = () => { const next = prompt('输入货币代码：CNY / USD / EUR / JPY', 'CNY'); if (!next || !['CNY', 'USD', 'EUR', 'JPY'].includes(next.toUpperCase())) return; const state = JSON.parse(localStorage.getItem('tw-state') || '{}'); state.currency = next.toUpperCase(); localStorage.setItem('tw-state', JSON.stringify(state)); render(); };
  window.toggleProfileLanguage = () => { const state = JSON.parse(localStorage.getItem('tw-state') || '{}'); state.lang = state.lang === 'en' ? 'zh' : 'en'; localStorage.setItem('tw-state', JSON.stringify(state)); document.querySelectorAll('.nav button').forEach((button, index) => { const zh = ['首页', '发现', '地图', '旅友', '我的']; const en = ['Home', 'Discover', 'Map', 'Buddies', 'Me']; const icon = button.querySelector('.nav-icon'); if (icon) button.innerHTML = '<span class="nav-icon">' + icon.textContent + '</span><br>' + (state.lang === 'en' ? en[index] : zh[index]); }); render(); };
  window.clearProfileCache = () => { ['tw-community-home', 'tw-buddy-state', 'tw-ai-context', 'tw-map-cache-v2', 'tw-plan'].forEach(key => localStorage.removeItem(key)); alert('本地缓存已清除'); render(); };
  window.logoutProfile = async () => { await window.TravelWorldAuth?.logout?.(); profile = null; stats = { trips: 0, followers: 0, likes: 0 }; render(); };
  const style = document.createElement('style'); style.textContent = '.profile-hero{display:flex;gap:16px;align-items:center;padding:8px 0 20px}.profile-large-avatar{width:78px;height:78px;border-radius:50%;object-fit:cover}.profile-hero h1{margin:0;color:#173f4f;font-size:26px}.profile-hero p{margin:6px 0 10px;color:#718087;font-size:13px}.profile-stats{display:flex;justify-content:space-around;text-align:center}.profile-stats div{display:flex;flex-direction:column;gap:5px}.profile-stats b{font-size:22px;color:#173f4f}.profile-stats span,.profile-links small{font-size:12px;color:#718087}.profile-links{display:grid;grid-template-columns:1fr 1fr;gap:1px}.profile-links button,.profile-settings button{border:0;background:transparent;text-align:left;color:#173f4f;padding:14px 4px;font:inherit}.profile-links button{display:flex;flex-direction:column;gap:4px}.profile-links button:first-letter{color:#d17d57}.profile-settings h3{margin:0 0 8px;color:#173f4f}.profile-settings button{display:flex;justify-content:space-between;border-top:1px solid #edf0ec;color:#53656b;font-size:14px}.profile-settings button span{color:#9aa5a5}.profile-settings .danger{color:#ba6449}'; document.head.appendChild(style);
  window.addEventListener('tw-auth-change', loadProfile); window.addEventListener('DOMContentLoaded', loadProfile); if (document.readyState !== 'loading') loadProfile();
}());
