(function () {
  const fields = { dest: ['输入目的地，例如大理', ''], budget: ['预算（CNY）', ''], date: ['出发日期', ''], days: ['旅行天数', ''], interest: ['兴趣，例如自然、美食、摄影', ''] };
  const auth = () => window.TravelWorldAuth;
  const safe = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  let communityRoutes = [], routeFavoriteIds = new Set(), seasonalDestinations = [], activeFilter='all';
  const lang=()=>window.TravelWorldI18n?.language?.()||'zh';
  const copy=(zh,en)=>lang()==='en'?en:zh;
  const routeEnglish={
    'cn-beijing-culture':{title:'Beijing Heritage · 4 Days',destination:'Beijing',country:'China',type:'Culture',audience:'First-time visitors interested in history, architecture and city walks',summary:'Read the old capital through its central axis, hutongs and Great Wall.',tags:['Forbidden City','Great Wall','Hutongs','Local food']},
    'cn-chengdu-food':{title:'Slow Food Chengdu · 3 Days',destination:'Chengdu',country:'China',type:'Food',audience:'Travelers who enjoy food, wildlife and a relaxed city pace',summary:'Pandas in the morning, teahouses in the afternoon and Sichuan flavors after dark.',tags:['Pandas','Teahouses','Sichuan food','Alleys']},
    'cn-dali-nature':{title:'Dali Mountains & Lake · 4 Days',destination:'Dali',country:'China',type:'Nature',audience:'Travelers who enjoy lakes, old towns, cycling and light hiking',summary:'Balance Dali Old Town, west-shore cycling, Cangshan and the open views east of Erhai Lake.',tags:['Erhai Lake','Cangshan','Xizhou','Sunset']},
    'cn-shanghai-city':{title:'Urban Shanghai · 3 Days',destination:'Shanghai',country:'China',type:'City',audience:'Travelers drawn to architecture, neighborhoods, museums and photography',summary:'Connect both sides of the Huangpu with plane-tree streets, museums and the Suzhou Creek waterfront.',tags:['The Bund','Wukang Road','Museums','Night views']}
  };
  const localized=item=>lang()==='en'?{...item,...(routeEnglish[item?.id]||{}),...(item?.en||{})}:item;
  function setup() {
    const style = document.createElement('style');
    style.textContent = '.route-filters{display:flex;flex-wrap:wrap;gap:4px;margin:12px 0}.route-grid{display:grid;grid-template-columns:1fr;gap:14px}.route-card-top{display:flex;justify-content:space-between;align-items:center}.route-tags{line-height:1.8}.map-controls{display:flex;gap:7px;align-items:center;margin-bottom:10px}.map-controls input{flex:1;padding:10px;border:1px solid #dfe6e1;border-radius:999px;font:inherit}.leaflet-container{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}';
    document.head.appendChild(style);
    Object.keys(fields).forEach(id => { const input = document.getElementById(id); if (input) { input.value = fields[id][1]; input.placeholder = fields[id][0]; } });
    const section = document.getElementById('mapExplore') || document.getElementById('discover');
    if (!section || document.getElementById('routeLibrary')) return;
    const library = document.createElement('div');
    library.id = 'routeLibrary';
    library.innerHTML = '<div class="head"><h2>参考路线</h2><span class="muted">中国 · 全球 · 徒步</span></div><div id="routeFilters" class="route-filters"></div><div id="routeGrid" class="route-grid"></div><div class="head"><h2>旅行者路线</h2><span class="muted">真实发布</span></div><div id="communityRouteGrid" class="route-grid"></div>';
    section.appendChild(library);
    const seasonal=document.createElement('section');seasonal.id='whereNow';seasonal.className='where-now';seasonal.innerHTML='<div class="head"><div><small>SEASONAL EDIT</small><h2>现在去哪儿</h2></div><span class="muted">按当季精选</span></div><div id="whereNowGrid" class="where-now-grid"></div>';
    const planner=section.querySelector(':scope>.card'),mapCard=document.querySelector('#map>.map-card-primary'),landmark=document.getElementById('landmarkCard');if(mapCard)section.insertBefore(mapCard,planner);section.insertBefore(seasonal,planner);if(landmark)section.insertBefore(landmark,library);
    Promise.all([fetch('modules/data/routes.json?v=4').then(response=>response.json()),fetch('modules/data/seasonal-destinations.json?v=2').then(response=>response.json())]).then(([routes,seasons])=>{window.travelRoutes=routes.routes;seasonalDestinations=seasons.destinations;renderSeasonal();renderRoutes('all');}).catch(() => { document.getElementById('routeGrid').textContent = '参考路线暂时无法加载，请检查网络后重试。'; });
    loadCommunityRoutes();
  }
  const filters=[['all','全部','All'],['china','中国','China'],['overseas','海外','Worldwide'],['southeast-asia','东南亚','Southeast Asia'],['east-asia','东亚','East Asia'],['europe','欧洲','Europe'],['north-america','北美','North America'],['hiking','徒步','Hiking']];
  function routeMatches(route,type){if(type==='all')return true;if(type==='china')return route.country==='中国';if(type==='overseas')return route.country!=='中国';if(type==='hiking')return route.routeType==='hiking';const regions={'southeast-asia':'东南亚','east-asia':'东亚','europe':'欧洲','north-america':'北美'};return route.region===regions[type];}
  function renderRoutes(type) {
    activeFilter=type;
    const routes = window.travelRoutes || [];
    const filtered = routes.filter(route=>routeMatches(route,type));
    document.getElementById('routeFilters').innerHTML = filters.map(item => '<button class="pill ' + (item[0] === type ? 'active' : '') + '" onclick="filterTravelRoutes(\'' + item[0] + '\')">' + copy(item[1],item[2]) + '</button>').join('');
    document.getElementById('routeGrid').innerHTML = filtered.map(source => {const route=localized(source);return '<article class="route-reference-card route-photo-loading" data-route-cover="' + safe(source.id) + '"><img class="route-reference-cover" alt="' + safe(route.destination) + '" loading="lazy" decoding="async"><div class="route-reference-shade"></div><div class="route-reference-copy"><div class="route-card-top"><span class="route-country">' + safe(route.country) + ' · ' + safe(route.destination) + '</span><span>' + route.days + ' '+copy('天','days')+'</span></div><div class="route-reference-main"><p>' + safe(route.type) + '</p><h3>' + safe(route.title) + '</h3><div class="route-tags">' + route.tags.slice(0,3).map(tag => '<span>#' + safe(tag) + '</span>').join(' ') + '</div><div class="route-reference-footer"><b>' + safe(route.budget) + '</b><button class="route-view-button" onclick="openTravelRoute(\'' + source.id + '\')">'+copy('查看路线','View route')+' <span>→</span></button></div></div></div></article>';}).join('');
    filtered.forEach(route => setRoutePhoto(document.querySelector('[data-route-cover="' + route.id + '"] img'), route.coverQuery));
  }
  window.filterTravelRoutes = renderRoutes;
  const setRoutePhoto=(image,query)=>window.TravelImageService.load(image,query);
  function renderSeasonal(){const month=new Date().getMonth()+1,items=seasonalDestinations.filter(item=>item.months.includes(month)).slice(0,8),root=document.getElementById('whereNowGrid');if(!root)return;root.innerHTML=items.map(source=>{const item=localized(source);return '<article class="where-now-card image-loading" data-season="'+safe(source.id)+'"><img alt="'+safe(item.title)+'"><div><small>'+safe(item.country)+' · '+safe(item.city)+'</small><h3>'+safe(item.title)+'</h3><p>'+safe(item.reason)+'</p><b>'+safe(item.experience)+'</b><em>'+safe(item.seasonalFood)+'</em><button onclick="openSeasonalDestination(\''+safe(source.id)+'\')">'+copy('查看路线','View route')+' →</button></div></article>';}).join('');items.forEach(item=>window.TravelImageService.load(root.querySelector('[data-season="'+item.id+'"] img'),item.imageQuery));window.TravelWorldI18n?.translate(root);}
  window.openSeasonalDestination=id=>{const item=seasonalDestinations.find(x=>x.id===id),route=(window.travelRoutes||[]).find(x=>x.id===item?.routeId);if(route)return openTravelRoute(route.id);const input=document.getElementById('dest');if(input)input.value=localized(item).city;document.querySelector('#mapExplore>.card')?.scrollIntoView({behavior:'smooth'});};
  window.refreshExploreLocale=()=>{renderSeasonal();renderRoutes(activeFilter);};
  const activityCard = (activity, routeId, dayNumber, index) => '<article class="route-activity route-photo-loading" data-route-photo="' + safe(routeId + '-' + dayNumber + '-' + index) + '"><div class="route-activity-image"><img alt="' + safe(activity.name) + '" loading="lazy" decoding="async"><span>' + safe(activity.time) + '</span></div><div class="route-activity-copy"><h4>' + safe(activity.name) + '</h4><p>' + safe(activity.description) + '</p><dl><div><dt>'+copy('建议停留','Suggested time')+'</dt><dd>' + safe(activity.duration) + '</dd></div><div><dt>'+copy('门票参考','Ticket guide')+'</dt><dd>' + safe(activity.ticket) + '</dd></div><div><dt>'+copy('怎么去','Getting there')+'</dt><dd>' + safe(activity.transport) + '</dd></div></dl><aside><b>'+copy('旅行提示','Travel tip')+'</b>' + safe(activity.tips) + '</aside></div></article>';
  function hikingInfo(route){if(route.routeType!=='hiking')return '';return '<section class="hiking-facts"><div><small>'+copy('起点 → 终点','Start → Finish')+'</small><b>'+safe(route.start)+' → '+safe(route.end)+'</b></div><div><small>'+copy('距离 / 累计爬升','Distance / Ascent')+'</small><b>'+route.distanceKm+' km · ↑ '+route.ascentM+' m</b></div><div><small>'+copy('难度 / 最佳季节','Difficulty / Best season')+'</small><b>'+safe(route.difficulty)+' · '+safe(route.bestSeason)+'</b></div><div><small>'+copy('装备建议','Gear')+'</small><b>'+safe(route.equipment)+'</b></div></section><div class="hiking-map" data-hiking-map aria-label="'+copy('徒步路线地图','Hiking route map')+'"></div><section class="hiking-notes"><div><small>'+copy('补给点','Supplies')+'</small><p>'+route.supplies.map(safe).join(' · ')+'</p></div><div><small>'+copy('住宿','Lodging')+'</small><p>'+safe(route.lodging)+'</p></div><div><small>'+copy('注意事项','Notes')+'</small><p>'+safe(route.notes)+'</p></div></section>';}
  function initHikingMap(root,route){if(!root||!window.L||!route.waypoints?.length)return null;const points=route.waypoints.map(p=>[p.latitude,p.longitude]),map=L.map(root,{scrollWheelZoom:false,attributionControl:false}).fitBounds(points,{padding:[24,24]});L.tileLayer(TravelMapProviders.get().tile,{maxZoom:19}).addTo(map);L.polyline(points,{color:'#a44938',weight:5,opacity:.9}).addTo(map);route.waypoints.forEach((point,index)=>L.marker([point.latitude,point.longitude],{icon:L.divIcon({className:'tw-route-pin',html:'<div class="tw-route-pin__body">'+(index+1)+'</div>',iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map).bindPopup('<b>'+safe(point.name)+'</b>'));setTimeout(()=>map.invalidateSize(),0);return map;}
  window.openTravelRoute = id => {
    const source = (window.travelRoutes || []).find(item => item.id === id); if (!source) return;const route=localized(source);
    document.getElementById('routeDetailOverlay')?.remove();
    const overlay = document.createElement('div'); overlay.id = 'routeDetailOverlay'; overlay.className = 'dm-overlay route-detail-overlay';
    overlay.innerHTML = '<article class="route-detail" role="dialog" aria-label="' + safe(route.title) + '"><header class="route-detail-hero route-photo-loading"><img alt="' + safe(route.destination) + '"><div class="route-detail-gradient"></div><button class="route-detail-back" data-close aria-label="返回">← '+copy('返回','Back')+'</button><div><span>CURATED JOURNEY · ' + safe(route.country) + '</span><h2>' + safe(route.title) + '</h2><p>' + safe(route.destination) + ' · ' + route.days + ' '+copy('天','days')+' · ' + safe(route.type) + '</p></div></header><section class="route-detail-intro"><div class="route-detail-facts"><span><small>'+copy('预算参考','Budget')+'</small><b>' + safe(route.budget) + '</b></span><span><small>'+copy('适合人群','Best for')+'</small><b>' + safe(route.audience) + '</b></span></div><p>' + safe(route.summary) + '</p><div class="route-tags">' + route.tags.map(tag => '<span>#' + safe(tag) + '</span>').join(' ') + '</div>'+hikingInfo(source)+'</section><section class="route-days">' + source.daysPlan.map(day => '<article class="route-day"><header><span>DAY ' + day.dayNumber + '</span><div><h3>' + safe(day.title) + '</h3><p>' + safe(day.summary) + '</p></div><b>' + safe(day.cost) + '</b></header>' + day.activities.map((activity, index) => activityCard(activity, source.id, day.dayNumber, index)).join('') + '<div class="route-day-notes"><div><small>'+copy('吃什么','Food')+'</small><p>' + safe(day.food) + '</p></div><div><small>'+copy('住哪里','Stay')+'</small><p>' + safe(day.stay) + '</p></div><div><small>'+copy('交通','Transport')+'</small><p>' + safe(day.transport) + '</p></div></div></article>').join('') + '</section><footer class="route-detail-actions"><button class="btn alt" data-close>'+copy('返回参考路线','Back to routes')+'</button><button class="btn" data-use>'+copy('按这条路线继续规划','Continue with this route')+'</button></footer><p class="route-photo-credit">'+copy('路线实景图片由 Wikimedia Commons 提供；票价与开放时间请以出行当天官方信息为准。','Route photos are provided by Wikimedia Commons; verify prices and opening hours before departure.')+'</p></article>';
    document.body.appendChild(overlay); document.body.classList.add('route-detail-open');
    setRoutePhoto(overlay.querySelector('.route-detail-hero img'), source.coverQuery);
    source.daysPlan.forEach(day => day.activities.forEach((activity, index) => setRoutePhoto(overlay.querySelector('[data-route-photo="' + source.id + '-' + day.dayNumber + '-' + index + '"] img'), activity.imageQuery)));const detailMap=initHikingMap(overlay.querySelector('[data-hiking-map]'),source);
    const close = () => { detailMap?.remove();overlay.remove(); document.body.classList.remove('route-detail-open'); };
    overlay.onclick = event => { if (event.target === overlay || event.target.closest('[data-close]')) close(); };
    overlay.querySelector('[data-use]').onclick = () => { close(); window.useTravelRoute(route.destination, route.days, route.tags.join('、')); };
  };
  async function loadCommunityRoutes() { const target = document.getElementById('communityRouteGrid'); if (!target) return; try { communityRoutes = await auth().request('/api/routes'); routeFavoriteIds = new Set(auth().session?.() ? await auth().request('/api/routes/favorites') : []); target.innerHTML = communityRoutes.length ? communityRoutes.map(route => { const liked = (route.route_likes || []).some(item => item.user_id === auth().session?.()?.user?.id), comments = route.route_comments || []; return '<article class="route-card">' + TravelPostUI.routeCard(route) + '<div class="route-card-top"><span class="pill">' + safe(route.owner?.display_name || '旅行者') + '</span><button class="post-map" onclick="openRouteDetail(\''+route.id+'\')">完整详情</button></div><div class="post-actions"><button onclick="toggleRouteLike(\'' + route.id + '\')">' + (liked ? '♥' : '♡') + ' ' + (route.route_likes?.length || 0) + '</button><button onclick="toggleRouteFavorite(\'' + route.id + '\')">' + (routeFavoriteIds.has(route.id) ? '★ 已收藏' : '☆ 收藏') + '</button><button onclick="commentRoute(\'' + route.id + '\')">评论 ' + comments.length + '</button></div>' + (comments.length ? '<div class="route-comments">' + comments.slice(-3).map(item => '<div>' + safe(item.author?.display_name || '旅行者') + '：' + safe(item.content) + '</div>').join('') + '</div>' : '') + '</article>'; }).join('') : '<div class="muted">还没有旅行者发布公开路线。</div>'; } catch (error) { target.innerHTML = '<div class="muted">旅行者路线暂时无法加载：' + safe(error.message) + '</div>'; } }
  window.toggleRouteLike = async id => { if (!auth().requireLogin()) return; try { await auth().request('/api/routes/' + id + '/like', { method: 'POST' }); await loadCommunityRoutes(); } catch (error) { alert(error.message); } };
  window.toggleRouteFavorite = async id => { if (!auth().requireLogin()) return; try { await auth().request('/api/routes/' + id + '/favorite', { method: 'POST' }); await loadCommunityRoutes(); } catch (error) { alert(error.message); } };
  window.commentRoute = async id => { if (!auth().requireLogin()) return; const content = prompt('写下对这条路线的评论：'); if (!content?.trim()) return; try { await auth().request('/api/routes/' + id + '/comments', { method: 'POST', body: JSON.stringify({ content: content.trim() }) }); await loadCommunityRoutes(); } catch (error) { alert(error.message); } };
  window.useTravelRoute = (destination, days, interest) => { document.getElementById('aiDest').value = destination; document.getElementById('aiDays').value = days; document.getElementById('aiInterest').value = interest; go('ai'); makePlan(); };
  window.addEventListener('tw-auth-change', loadCommunityRoutes); if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', setup); else setup();
}());
