(function () {
  const auth = () => window.TravelWorldAuth;
  const safe = value => String(value || '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  let posts = [], selectedFiles = [], favoriteIds = new Set(), followingIds = new Set(), currentFeed = 'recommend', publishing = false, publishRequestId = '';
  function normalize(post) { const profile = post.profiles || {}, media = (post.post_media || []).sort((a, b) => a.sort_order - b.sort_order)[0]; return { ...post, user: profile.display_name || profile.username || '旅行者', text: post.content, location: post.location_name || [post.city, post.country].filter(Boolean).join(', '), image: media?.public_url, mediaType: media?.media_type, likes: (post.post_likes || []).length, liked: (post.post_likes || []).some(x => x.user_id === auth().session()?.user?.id), favorited: favoriteIds.has(post.id), comments: post.comments || [] }; }
  function render() { const target = document.getElementById('communityFeed'); if (!target) return; const uid = auth().session()?.user?.id; target.innerHTML = posts.length ? posts.map(raw => { const p = normalize(raw), media = p.image ? (p.mediaType === 'video' ? '<video class="post-image" controls preload="metadata" src="' + safe(p.image) + '"></video>' : '<img class="post-image" loading="lazy" decoding="async" src="' + safe(p.image) + '" alt="' + safe(p.title) + '">') : '', followed = followingIds.has(p.author_id), avatar = p.profiles?.avatar_url; return '<article class="post-card">' + media + '<div class="post-content"><div class="post-author"><div class="post-author-identity" role="button" tabindex="0" onclick="openTravelUser(\'' + p.author_id + '\')">' + (avatar ? '<img src="' + safe(avatar) + '" alt="">' : '<span class="post-avatar-fallback">TW</span>') + '<div><div class="post-author-name">' + safe(p.user) + '</div><button class="post-location post-map" onclick="event.stopPropagation();openCommunityLocation(\'' + safe(p.city || p.location) + '\')">' + safe(p.location || '未标注地点') + '</button></div></div>' + (p.author_id !== uid ? '<button class="post-map" onclick="toggleCommunityFollow(\'' + p.author_id + '\')">' + (followed ? '已关注' : '关注') + '</button>' : '') + '</div><div class="post-title">' + safe(p.title) + '</div><div class="post-copy">' + safe(p.text) + '</div><div class="post-actions"><button class="' + (p.liked ? 'is-liked' : '') + '" onclick="toggleCommunityLike(\'' + p.id + '\')">' + (p.liked ? '♥' : '♡') + ' ' + p.likes + '</button><button onclick="toggleCommunityFavorite(\'' + p.id + '\')">' + (p.favorited ? '★ 已收藏' : '☆ 收藏') + '</button><span>评论 ' + p.comments.length + '</span><button onclick="openCommunityLocation(\'' + safe(p.city || p.location) + '\')" class="post-map">进入地图</button></div><div class="comment-row"><input data-comment-input="' + p.id + '" placeholder="写下你的旅行感受"><button onclick="addCommunityComment(\'' + p.id + '\')">评论</button></div>' + (p.comments.length ? '<div class="post-comments">' + p.comments.slice(-4).map(c => '<div>· <b>' + safe(c.profiles?.display_name || '旅行者') + '</b>：' + safe(c.content) + ((c.author_id === uid || p.author_id === uid) ? '<button onclick="deleteCommunityComment(\'' + c.id + '\')">删除</button>' : '') + '</div>').join('') + '</div>' : '') + '</div></article>'; }).join('') : '<div class="card"><div class="muted">还没有旅行分享，登录后发布第一篇内容。</div></div>'; }
  async function load() { try { posts = await auth().request(currentFeed === 'following' ? '/api/community/feed/following' : '/api/community/feed'); favoriteIds = new Set(); followingIds = new Set(); if (auth().session?.()) { const [favorites, following] = await Promise.all([auth().request('/api/community/favorites'), auth().request('/api/community/following')]); favoriteIds = new Set(favorites.map(post => post.id)); followingIds = new Set(following.map(user => user.id)); } render(); } catch (e) { if (!auth().session?.() && currentFeed === 'recommend') { try { posts = await auth().request('/api/community/feed'); return render(); } catch (_) {} } document.getElementById('communityFeed').innerHTML = '<div class="card"><div class="muted">暂时无法连接社区服务：' + safe(e.message) + '</div></div>'; } }
  window.setFeed = async feed => { if (feed === 'following' && !auth().requireLogin()) return; currentFeed = feed; document.getElementById('recommendTab')?.classList.toggle('active', feed === 'recommend'); document.getElementById('followingTab')?.classList.toggle('active', feed === 'following'); await load(); };
  window.toggleComposer = () => { if (auth().requireLogin()) document.getElementById('composePanel').classList.toggle('open'); };
  function renderMediaList() { const target = document.getElementById('composeMediaList'); const hint = document.getElementById('composeMediaHint'); if (!target || !hint) return; hint.textContent = selectedFiles.length ? '已选择 ' + selectedFiles.length + ' 个文件，可继续添加或删除' : '可选择照片、视频或实况照片'; target.innerHTML = selectedFiles.map((file, index) => '<span class="pill">' + safe(file.name) + ' <button type="button" onclick="removeCommunityMedia(' + index + ')" style="border:0;background:transparent;color:inherit;cursor:pointer">×</button></span>').join(''); }
  window.selectCommunityMedia = event => { selectedFiles = selectedFiles.concat(Array.from(event.target.files || [])).slice(0, 8); event.target.value = ''; renderMediaList(); };
  window.removeCommunityMedia = index => { selectedFiles.splice(index, 1); renderMediaList(); };
  window.publishPost = async () => { if (publishing||!auth().requireLogin()) return; const title = document.getElementById('composeTitle').value.trim(), content = document.getElementById('composeText').value.trim(), location_name = document.getElementById('composeLocation').value.trim(), button = document.getElementById('publishPostButton'); if (!title || !content) return auth().toast?.('请填写标题和内容'); publishing=true;publishRequestId||=crypto.randomUUID();button.disabled = true; button.setAttribute('aria-busy','true');button.textContent = '正在发布…'; try { const type = selectedFiles.some(file => file.type.startsWith('video/')) ? 'video' : selectedFiles.length ? 'photo' : 'story'; const post = await auth().request('/api/community/posts', { method: 'POST',headers:{'Idempotency-Key':publishRequestId}, body: JSON.stringify({ title, content, location_name, city: location_name.split(',')[0], type,clientRequestId:publishRequestId }) }); for (let index = 0; index < selectedFiles.length; index += 1) { button.textContent = '正在上传 ' + (index + 1) + '/' + selectedFiles.length + '…'; const form = new FormData(); form.append('file', selectedFiles[index]); await auth().request('/api/community/posts/' + post.id + '/media', { method: 'POST', body: form }); } ['composeTitle','composeText','composeLocation'].forEach(id => document.getElementById(id).value = ''); selectedFiles = [];publishRequestId=''; renderMediaList(); document.getElementById('composePanel').classList.remove('open'); await load(); auth().toast?.('发布成功'); } catch (e) { auth().toast?.('发布失败：' + e.message); } finally { publishing=false;button.disabled = false;button.removeAttribute('aria-busy'); button.textContent = '发布到首页'; } };
  window.toggleCommunityLike = async id => { if (!auth().requireLogin()) return; const post = posts.find(item => item.id === id); if (!post) return; const uid = auth().session().user.id, prior = post.post_likes || [], liked = prior.some(item => item.user_id === uid); post.post_likes = liked ? prior.filter(item => item.user_id !== uid) : prior.concat({ user_id: uid }); render(); try { const result = await auth().request('/api/community/posts/' + id + '/like', { method: 'POST' }); const current = posts.find(item => item.id === id); if (current) current.post_likes = result.liked ? [{ user_id: uid }, ...current.post_likes.filter(item => item.user_id !== uid)] : current.post_likes.filter(item => item.user_id !== uid); render(); } catch (e) { post.post_likes = prior; render(); alert('点赞未同步：' + e.message); } };
  window.toggleCommunityFavorite = async id => { if (!auth().requireLogin()) return; const before = favoriteIds.has(id); before ? favoriteIds.delete(id) : favoriteIds.add(id); render(); try { const result = await auth().request('/api/community/posts/' + id + '/favorite', { method: 'POST' }); result.favorited ? favoriteIds.add(id) : favoriteIds.delete(id); render(); } catch (_) { before ? favoriteIds.add(id) : favoriteIds.delete(id); render(); auth().toast?.('操作失败，请重试'); } };
  window.addCommunityComment = async id => { if (!auth().requireLogin()) return; const input = document.querySelector('[data-comment-input="' + id + '"]'), content = input?.value.trim(); if (!content) return; const post = posts.find(item => item.id === id), uid = auth().session().user.id, profile = auth().session().user.user_metadata || {}; const optimistic = { id: 'pending-' + Date.now(), author_id: uid, content, profiles: { display_name: profile.display_name || profile.name || '我' } }; post.comments = (post.comments || []).concat(optimistic); input.value = ''; render(); try { const saved = await auth().request('/api/community/posts/' + id + '/comments', { method: 'POST', body: JSON.stringify({ content }) }); post.comments = post.comments.map(item => item.id === optimistic.id ? saved : item); render(); auth().toast?.('评论成功'); } catch (e) { post.comments = post.comments.filter(item => item.id !== optimistic.id); render(); alert('评论未发布：' + e.message); } };
  window.deleteCommunityComment = async id => { if (!auth().requireLogin() || !confirm('删除这条评论？')) return; let owner, removed, index; for (const post of posts) { const at = (post.comments || []).findIndex(item => item.id === id); if (at >= 0) { owner = post; index = at; removed = post.comments.splice(at, 1)[0]; break; } } render(); try { await auth().request('/api/community/comments/' + id, { method: 'DELETE' }); auth().toast?.('删除成功'); } catch (_) { if (owner && removed) owner.comments.splice(index, 0, removed); render(); auth().toast?.('操作失败，请重试'); } };
  window.toggleCommunityFollow = async id => { if (!auth().requireLogin()) return; const before = followingIds.has(id); before ? followingIds.delete(id) : followingIds.add(id); render(); try { const result = await auth().request('/api/community/users/' + id + '/follow', { method: 'POST' }); result.following ? followingIds.add(id) : followingIds.delete(id); render(); } catch (_) { before ? followingIds.add(id) : followingIds.delete(id); render(); auth().toast?.('操作失败，请重试'); } };
  window.openCommunityLocation = city => { go('map'); loadMap(); setTimeout(() => window.searchTravelMap?.(city), 400); };
  const style = document.createElement('style'); style.textContent = '.post-author-identity{display:flex;align-items:center;gap:9px;min-width:0}.post-author-identity img,.post-avatar-fallback{width:36px;height:36px;border-radius:50%;object-fit:cover;flex:0 0 auto}.post-avatar-fallback{display:grid;place-items:center;background:#e8eee9;color:#173f4f;font-size:11px;font-weight:800}.post-author{align-items:center}.post-actions{align-items:center;flex-wrap:wrap;gap:12px}.post-comments{font-size:12px;color:#718087;margin-top:10px;display:grid;gap:6px}.post-comments button{border:0;background:transparent;color:#ba6449;margin-left:6px;padding:0}'; document.head.appendChild(style);
  window.addEventListener('tw-auth-change', load); load();
}());
