(function () {
  const auth = () => window.TravelWorldAuth;
  const safe = value => String(value || '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  let posts = [], selectedFile = null, favoriteIds = new Set(), followingIds = new Set(), currentFeed = 'recommend';
  function normalize(post) { const profile = post.profiles || {}, media = (post.post_media || []).sort((a, b) => a.sort_order - b.sort_order)[0]; return { ...post, user: profile.display_name || profile.username || '旅行者', text: post.content, location: post.location_name || [post.city, post.country].filter(Boolean).join(', '), image: media?.public_url, mediaType: media?.media_type, likes: (post.post_likes || []).length, liked: (post.post_likes || []).some(x => x.user_id === auth().session()?.user?.id), favorited: favoriteIds.has(post.id), comments: post.comments || [] }; }
  function render() { const target = document.getElementById('communityFeed'); if (!target) return; const uid = auth().session()?.user?.id; target.innerHTML = posts.length ? posts.map(raw => { const p = normalize(raw), media = p.image ? (p.mediaType === 'video' ? '<video class="post-image" controls preload="metadata" src="' + safe(p.image) + '"></video>' : '<img class="post-image" src="' + safe(p.image) + '" alt="' + safe(p.title) + '">') : '', followed = followingIds.has(p.author_id), avatar = p.profiles?.avatar_url; return '<article class="post-card">' + media + '<div class="post-content"><div class="post-author"><div class="post-author-identity">' + (avatar ? '<img src="' + safe(avatar) + '" alt="">' : '<span class="post-avatar-fallback">TW</span>') + '<div><div class="post-author-name">' + safe(p.user) + '</div><button class="post-location post-map" onclick="openCommunityLocation(\'' + safe(p.city || p.location) + '\')">' + safe(p.location || '未标注地点') + '</button></div></div>' + (p.author_id !== uid ? '<button class="post-map" onclick="toggleCommunityFollow(\'' + p.author_id + '\')">' + (followed ? '已关注' : '关注') + '</button>' : '') + '</div><div class="post-title">' + safe(p.title) + '</div><div class="post-copy">' + safe(p.text) + '</div><div class="post-actions"><button class="' + (p.liked ? 'is-liked' : '') + '" onclick="toggleCommunityLike(\'' + p.id + '\')">' + (p.liked ? '♥' : '♡') + ' ' + p.likes + '</button><button onclick="toggleCommunityFavorite(\'' + p.id + '\')">' + (p.favorited ? '★ 已收藏' : '☆ 收藏') + '</button><span>评论 ' + p.comments.length + '</span><button onclick="openCommunityLocation(\'' + safe(p.city || p.location) + '\')" class="post-map">进入地图</button></div><div class="comment-row"><input data-comment-input="' + p.id + '" placeholder="写下你的旅行感受"><button onclick="addCommunityComment(\'' + p.id + '\')">评论</button></div>' + (p.comments.length ? '<div class="post-comments">' + p.comments.slice(-4).map(c => '<div>· <b>' + safe(c.profiles?.display_name || '旅行者') + '</b>：' + safe(c.content) + ((c.author_id === uid || p.author_id === uid) ? '<button onclick="deleteCommunityComment(\'' + c.id + '\')">删除</button>' : '') + '</div>').join('') + '</div>' : '') + '</div></article>'; }).join('') : '<div class="card"><div class="muted">还没有旅行分享，登录后发布第一篇内容。</div></div>'; }
  async function load() { try { posts = await auth().request(currentFeed === 'following' ? '/api/community/feed/following' : '/api/community/feed'); favoriteIds = new Set(); followingIds = new Set(); if (auth().session?.()) { const [favorites, following] = await Promise.all([auth().request('/api/community/favorites'), auth().request('/api/community/following')]); favoriteIds = new Set(favorites.map(post => post.id)); followingIds = new Set(following.map(user => user.id)); } render(); } catch (e) { if (!auth().session?.() && currentFeed === 'recommend') { try { posts = await auth().request('/api/community/feed'); return render(); } catch (_) {} } document.getElementById('communityFeed').innerHTML = '<div class="card"><div class="muted">暂时无法连接社区服务：' + safe(e.message) + '</div></div>'; } }
  window.setFeed = async feed => { if (feed === 'following' && !auth().requireLogin()) return; currentFeed = feed; document.getElementById('recommendTab')?.classList.toggle('active', feed === 'recommend'); document.getElementById('followingTab')?.classList.toggle('active', feed === 'following'); await load(); };
  window.toggleComposer = () => { if (auth().requireLogin()) document.getElementById('composePanel').classList.toggle('open'); };
  window.selectCommunityMedia = event => { selectedFile = event.target.files?.[0] || null; document.getElementById('composeMediaHint').textContent = selectedFile ? selectedFile.name + ' 已选择' : '可选择一张照片或短视频'; };
  window.publishPost = async () => { if (!auth().requireLogin()) return; const title = document.getElementById('composeTitle').value.trim(), content = document.getElementById('composeText').value.trim(), location_name = document.getElementById('composeLocation').value.trim(); if (!title || !content) return alert('请填写标题和内容'); try { const post = await auth().request('/api/community/posts', { method: 'POST', body: JSON.stringify({ title, content, location_name, city: location_name.split(',')[0], type: selectedFile?.type.startsWith('video/') ? 'video' : selectedFile ? 'photo' : 'story' }) }); if (selectedFile) { const form = new FormData(); form.append('file', selectedFile); await auth().request('/api/community/posts/' + post.id + '/media', { method: 'POST', body: form }); } ['composeTitle','composeText','composeLocation'].forEach(id => document.getElementById(id).value = ''); selectedFile = null; document.getElementById('composePanel').classList.remove('open'); await load(); } catch (e) { alert('发布失败：' + e.message); } };
  window.toggleCommunityLike = async id => { if (!auth().requireLogin()) return; try { await auth().request('/api/community/posts/' + id + '/like', { method: 'POST' }); await load(); } catch (e) { alert(e.message); } };
  window.toggleCommunityFavorite = async id => { if (!auth().requireLogin()) return; try { await auth().request('/api/community/posts/' + id + '/favorite', { method: 'POST' }); await load(); } catch (e) { alert(e.message); } };
  window.addCommunityComment = async id => { if (!auth().requireLogin()) return; const input = document.querySelector('[data-comment-input="' + id + '"]'); if (!input?.value.trim()) return; try { await auth().request('/api/community/posts/' + id + '/comments', { method: 'POST', body: JSON.stringify({ content: input.value.trim() }) }); await load(); } catch (e) { alert(e.message); } };
  window.deleteCommunityComment = async id => { if (!auth().requireLogin() || !confirm('删除这条评论？')) return; try { await auth().request('/api/community/comments/' + id, { method: 'DELETE' }); await load(); } catch (e) { alert(e.message); } };
  window.toggleCommunityFollow = async id => { if (!auth().requireLogin()) return; try { const result = await auth().request('/api/community/users/' + id + '/follow', { method: 'POST' }); result.following ? followingIds.add(id) : followingIds.delete(id); render(); } catch (e) { alert(e.message); } };
  window.openCommunityLocation = city => { go('map'); loadMap(); setTimeout(() => window.searchTravelMap?.(city), 400); };
  const style = document.createElement('style'); style.textContent = '.post-author-identity{display:flex;align-items:center;gap:9px;min-width:0}.post-author-identity img,.post-avatar-fallback{width:36px;height:36px;border-radius:50%;object-fit:cover;flex:0 0 auto}.post-avatar-fallback{display:grid;place-items:center;background:#e8eee9;color:#173f4f;font-size:11px;font-weight:800}.post-author{align-items:center}.post-actions{align-items:center;flex-wrap:wrap;gap:12px}.post-comments{font-size:12px;color:#718087;margin-top:10px;display:grid;gap:6px}.post-comments button{border:0;background:transparent;color:#ba6449;margin-left:6px;padding:0}'; document.head.appendChild(style);
  window.addEventListener('tw-auth-change', load); load();
}());
