(function () {
  const base = location.protocol === 'file:' ? 'http://localhost:8787' : '';
  const key = 'tw-auth-session';
  let session = JSON.parse(localStorage.getItem(key) || 'null');
  function toast(message) { let node = document.getElementById('twToast'); if (!node) { node = document.createElement('div'); node.id = 'twToast'; node.style.cssText = 'position:fixed;z-index:30;left:50%;bottom:88px;transform:translateX(-50%);background:#173f4f;color:#fff;padding:10px 16px;border-radius:999px;font-size:13px;box-shadow:0 8px 22px #173f4f33'; document.body.appendChild(node); } node.textContent = message; node.hidden = false; clearTimeout(node._timer); node._timer = setTimeout(() => { node.hidden = true; }, 2200); }
  function saveSession(value) { session = value || null; try { if (session) localStorage.setItem(key, JSON.stringify(session)); else localStorage.removeItem(key); } catch (_) {} }
  let refreshing = null;
  async function refreshSession() { if (!session?.refresh_token) return false; if (!refreshing) refreshing = fetch(base + '/api/auth/refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refreshToken: session.refresh_token }) }).then(async response => { const body = await response.json().catch(() => ({})); if (!response.ok || !body.session) return false; saveSession(body.session); return true; }).catch(() => false).finally(() => { refreshing = null; }); return refreshing; }
  async function request(path, options = {}, retried = false) { const headers = { ...(options.headers || {}) }; if (!(options.body instanceof FormData)) headers['Content-Type'] = 'application/json'; if (session?.access_token) headers.Authorization = 'Bearer ' + session.access_token; const owner = session?.user?.id; const response = await fetch(base + path, { ...options, headers, signal: options.signal || AbortSignal.timeout(15000) }); if (owner !== session?.user?.id) throw new Error('账号已切换，请重试'); if (response.status === 401 && session && !retried && await refreshSession()) return request(path, options, true); const body = response.status === 204 ? null : await response.json().catch(() => ({})); if (response.status === 401 && session) { saveSession(null); render(); window.dispatchEvent(new Event('tw-auth-change')); } if (!response.ok) throw new Error(body?.error || '请求失败'); return body; }
  function getDialog() { let node = document.getElementById('authDialog'); if (!node) { node = document.createElement('dialog'); node.id = 'authDialog'; node.style.cssText = 'border:0;border-radius:12px;padding:20px;width:min(390px,calc(100% - 32px));box-shadow:0 20px 60px #173f4f33'; document.body.appendChild(node); } return node; }
  function show(mode = 'login') { const node = getDialog(), registering = mode === 'register'; node.innerHTML = '<form id="authForm"><div class="head" style="margin:0 0 12px"><h2>' + (registering ? '注册 Travel World' : '登录 Travel World') + '</h2><button type="button" class="post-map" id="authClose">关闭</button></div>' + (registering ? '<input class="input" name="displayName" placeholder="昵称" required>' : '') + '<input class="input" name="email" type="email" placeholder="邮箱" required><input class="input" name="password" type="password" minlength="8" placeholder="密码（至少 8 位）" required><button class="btn" type="submit">' + (registering ? '创建账号' : '登录') + '</button> <button class="btn alt" type="button" id="authSwitch">' + (registering ? '已有账号' : '注册账号') + '</button><div id="authError" class="muted" style="margin-top:10px"></div></form>'; node.showModal(); node.querySelector('#authClose').onclick = () => node.close(); node.querySelector('#authSwitch').onclick = () => show(registering ? 'login' : 'register'); node.querySelector('#authForm').onsubmit = async event => { event.preventDefault(); const output = node.querySelector('#authError'); output.textContent = '正在连接…'; try { const result = await request('/api/auth/' + mode, { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); if (!result.session) { output.textContent = '注册成功！请打开邮箱，点击验证链接完成邮箱验证，再返回登录。'; toast('邮箱验证邮件已发送'); return; } saveSession(result.session); await request('/api/auth/session'); node.close(); render(); window.dispatchEvent(new Event('tw-auth-change')); toast('登录成功'); } catch (error) { output.textContent = error.message; } }; }
  async function logout() { let failed = false; try { if (session) await request('/api/auth/logout', { method: 'POST' }); } catch (_) { failed = true; } saveSession(null); render(); window.dispatchEvent(new Event('tw-auth-change')); toast(failed ? '已退出此设备；服务端退出未确认' : '退出成功'); }
  function render() { const top = document.querySelector('.community-top'); if (!top) return; let button = document.getElementById('authEntry'); if (session) { button?.remove(); return; } if (!button) { button = document.createElement('button'); button.id = 'authEntry'; button.className = 'post-map'; top.insertBefore(button, top.lastElementChild); } button.textContent = '登录'; button.onclick = () => show('login'); }
  window.TravelWorldAuth = { request, session: () => session, requireLogin: () => session ? true : (show('login'), false), showLogin: () => show('login'), logout, toast }; render();
  const verified=new URLSearchParams(location.search).get('verified');if(verified){history.replaceState({},'',location.pathname);toast('邮箱验证成功，请登录');setTimeout(()=>show('login'),450)}
  else if (location.hash.includes('access_token=') || new URLSearchParams(location.search).get('type') === 'signup') location.replace('/auth-confirm.html'+location.search+location.hash);
}());
