(function () {
  const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const list=(value,fallback)=>Array.isArray(value)&&value.length?value:fallback;
  window.closeLandmarkDetail=()=>document.getElementById('landmarkDetailOverlay')?.remove();
  window.showLandmark=item=>{
    window.currentMapLandmark=item;
    const root=document.getElementById('landmarkCard');if(!root)return;
    const photos=[...(item.image?[{url:item.image,title:item.name,source:'Travel World'}]:[]),...(item.photos||[])].filter((photo,index,all)=>all.findIndex(other=>other.url===photo.url)===index).slice(0,6);
    const nearby=list(item.nearby,['城市中心','当地博物馆','周边历史街区']);
    const food=list(item.food,['当地代表菜','传统小吃']);
    const routes=(window.travelRoutes||[]).filter(route=>route.destination===item.city||route.destination===item.country||route.country===item.country).slice(0,3);
    window.closeLandmarkDetail();
    const overlay=document.createElement('div');overlay.id='landmarkDetailOverlay';overlay.className='landmark-sheet-overlay';
    overlay.innerHTML='<article class="landmark-sheet" role="dialog" aria-label="'+safe(item.name)+'详情"><button class="landmark-sheet-back" onclick="closeLandmarkDetail()">← 返回地图</button><header><span>'+safe(item.country)+' · '+safe(item.city)+'</span><h2>'+safe(item.name)+'</h2><p>'+safe(item.description)+'</p></header>'+(photos.length?'<div class="landmark-sheet-gallery">'+photos.map((photo,index)=>'<figure class="'+(index===0?'featured':'')+'"><img src="'+safe(photo.url)+'" loading="lazy" decoding="async" alt="'+safe(photo.title||item.name)+'"><figcaption>'+safe(photo.author||photo.source||'实景图片')+'</figcaption></figure>').join('')+'</div>':'<div class="landmark-photo-loading">热门图片暂时不可用</div>')+'<section class="landmark-facts"><div><small>推荐玩法</small><p>'+safe(list(item.tags,[]).join(' · ')||'城市漫步与文化体验')+'</p></div><div><small>建议时长</small><p>'+safe(item.duration||'2–4 小时')+'</p></div><div><small>最佳时间</small><p>'+safe(item.bestSeason||'以当地季节为准')+'</p></div><div><small>住宿区域</small><p>'+safe(item.stay||item.city+'市中心或公共交通沿线')+'</p></div><div><small>到达建议</small><p>'+safe(item.transport||'优先使用当地公共交通或持牌运营服务')+'</p></div><div><small>当地美食</small><p>'+food.map(safe).join(' · ')+'</p></div></section><section class="landmark-nearby"><h3>周边值得去</h3><div>'+nearby.map(place=>'<span>'+safe(place)+'</span>').join('')+'</div></section><section class="landmark-map-link"><div><small>地图位置</small><b>'+Number(item.latitude).toFixed(4)+', '+Number(item.longitude).toFixed(4)+'</b></div><a href="https://www.openstreetmap.org/?mlat='+encodeURIComponent(item.latitude)+'&mlon='+encodeURIComponent(item.longitude)+'#map=13/'+encodeURIComponent(item.latitude)+'/'+encodeURIComponent(item.longitude)+'" target="_blank" rel="noopener">打开地图 ↗</a></section><section class="landmark-related"><h3>相关热门路线</h3>'+(routes.length?routes.map(route=>'<button onclick="closeLandmarkDetail();openTravelRoute(\''+safe(route.id)+'\')"><b>'+safe(route.title)+'</b><span>'+safe(route.days)+' 天 · '+safe(route.type)+' →</span></button>').join(''):'<p class="muted">暂时没有匹配路线，可让 AI 为这里生成一条。</p>')+'</section><div class="landmark-sheet-actions"><button class="btn" onclick="addLandmark(\''+safe(item.id)+'\')">加入我的路线</button><button class="btn alt" onclick="planLandmarkWithAi(\''+safe(item.id)+'\')">用这个地点生成 AI 路线</button></div><small class="landmark-source">实景图片由 Wikimedia Commons 等公开来源提供；票价、开放时间与安全信息请在出发前核实。</small></article>';
    document.body.appendChild(overlay);overlay.onclick=event=>{if(event.target===overlay)window.closeLandmarkDetail();};root.innerHTML='';
  };
}());
